#!/bin/bash
# vim: ft=sh
set -eo pipefail

CONFIG="${HOME}/.pants/config"

case ${1:-status} in
  install|statisfy|update|upgrade)
    bork satisfy $CONFIG
    ;;
  check|status)
    bork status $CONFIG
    ;;
  *)
    echo "Usage: $0 [install|status]"
    exit 1
    ;;
esac

exit 0
